import { CATEGORIES } from "@/constants/categories";

export const challenges = [
  {
    id: 1,
    title: "Выучи 50&nbsp;глаголов в&nbsp;английском языке",
    description:
      "Каждый день изучай новые и повторяй пройденные глаголы английского языка, чтобы приблизиться к цели.",
    category: CATEGORIES.ENGLISH_LANGUAGE,
    isLiked: false,
    isActive: false,
    isFinished: false,
  },
  {
    id: 2,
    title: "Начни вставать в&nbsp;6&nbsp;утра",
    category: CATEGORIES.MENTAL_HEALTH,
    isLiked: true,
    isActive: false,
    isFinished: false,
  },
  {
    id: 3,
    title: "Начни медитировать",
    category: CATEGORIES.MENTAL_HEALTH,
    isLiked: false,
    isActive: true,
    isFinished: false,
  },
  {
    id: 4,
    title: "Основы инвестирования",
    category: CATEGORIES.FINANCES,
    isLiked: false,
    isActive: false,
    isFinished: false,
  },
  {
    id: 5,
    title: "Держи планку 21&nbsp;день",
    category: CATEGORIES.SPORT,
    isLiked: true,
    isActive: false,
    isFinished: true,
  },
  {
    id: 6,
    title: "Правильный завтрак",
    category: CATEGORIES.NUTRITION,
    isLiked: true,
    isActive: false,
    isFinished: false,
  },
  {
    id: 7,
    title: "Начни медитировать",
    category: CATEGORIES.MENTAL_HEALTH,
    isLiked: false,
    isActive: true,
    isFinished: false,
  },
  {
    id: 8,
    title: "Основы инвестирования",
    category: CATEGORIES.FINANCES,
    isLiked: false,
    isActive: false,
    isFinished: false,
  },
  {
    id: 9,
    title: "Держи планку 21&nbsp;день",
    category: CATEGORIES.SPORT,
    isLiked: false,
    isActive: false,
    isFinished: true,
  },
  {
    id: 10,
    title: "Правильный завтрак",
    category: CATEGORIES.NUTRITION,
    isLiked: true,
    isActive: false,
    isFinished: false,
  },
];
